import React, { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import type { inferProcedureOutput } from "@trpc/server";
import type { AppRouter } from "@acme/api";
import Image from "next/image";
import TopBar from "../../components/TopBar/topbar";
import { useAuth } from "@clerk/nextjs";

const Home: NextPage = () => {
  const { isSignedIn } = useAuth();

  return (
    <>
      <Head>
        <title>inrvana.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#f3c38f] to-[#484979] text-white">
        <TopBar />
        {/* Hero section */}
        {isSignedIn && <></>}
        {!isSignedIn && (
          <section className="flex flex-col items-center justify-center gap-4 pt-8">
            {/* create row to put image on side of header */}
            <Image
              width={256}
              height={256}
              src="/Hero.png"
              alt="lotus"
              className="h-64 w-64 rounded-full	"
            />
            <div className="flex flex-row items-center justify-center gap-4">
              <h1 className="text-center text-4xl font-bold">
                Welcome to inrvana.
              </h1>
            </div>
            <p className="text-center text-2xl">
              A tool to help you find your inner peace.
            </p>
          </section>
        )}
        {/* Features section */}
      </main>
    </>
  );
};

Home.getInitialProps = ({ res, err }: any) => {
  const statusCode = res ? res.statusCode : err ? err.statusCode : 404;
  return { statusCode };
};

export default Home;
